-- SHEKHAR EVENTS SUPABASE SETUP
-- Run this in Supabase Dashboard -> SQL Editor.
-- Before using uploads, create ONE admin user in Authentication -> Users.
-- Replace YOUR_ADMIN_EMAIL below with that exact admin email.

create table if not exists public.photos (
  id bigint generated by default as identity primary key,
  title text,
  storage_path text not null unique,
  created_at timestamptz not null default now()
);

alter table public.photos enable row level security;

drop policy if exists "Public can view photos" on public.photos;
create policy "Public can view photos"
on public.photos for select
to anon, authenticated
using (true);

drop policy if exists "Admin can insert photos" on public.photos;
create policy "Admin can insert photos"
on public.photos for insert
to authenticated
with check ((auth.jwt() ->> 'email') = 'YOUR_ADMIN_EMAIL');

drop policy if exists "Admin can delete photos" on public.photos;
create policy "Admin can delete photos"
on public.photos for delete
to authenticated
using ((auth.jwt() ->> 'email') = 'YOUR_ADMIN_EMAIL');

insert into storage.buckets (id, name, public)
values ('event-photos', 'event-photos', true)
on conflict (id) do update set public = true;

drop policy if exists "Public can view event photos" on storage.objects;
create policy "Public can view event photos"
on storage.objects for select
to public
using (bucket_id = 'event-photos');

drop policy if exists "Admin can upload event photos" on storage.objects;
create policy "Admin can upload event photos"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'event-photos'
  and (auth.jwt() ->> 'email') = 'YOUR_ADMIN_EMAIL'
);

drop policy if exists "Admin can delete event photos" on storage.objects;
create policy "Admin can delete event photos"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'event-photos'
  and (auth.jwt() ->> 'email') = 'YOUR_ADMIN_EMAIL'
);
